### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by zchmielewska** [acturtle/cashflower#257]
```
C:\Users\admin\Desktop\Projects\modelling\venv\Scripts\python.exe C:\Users\admin\Desktop\Projects\modelling\lifelib_cashflower\savings\run.py 
09:32:55 | Building model 'savings'
09:32:55 | Total number of model points: 100000
09:32:55 | Multiprocessing on 4 cores
09:32:55 | Calculation of ca. 25000 model points per core
[##------------------] 12% multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\Projects\modelling\venv\Lib\site-packages\cashflower\start.py", line 202, in start_multiprocessing
    output = model.run(part)
             ^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\Projects\modelling\venv\Lib\site-packages\cashflower\cashflow.py", line 266, in run
    results = [*map(p, range(range_start, range_end))]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\Projects\modelling\venv\Lib\site-packages\cashflower\cashflow.py", line 342, in calculate_model_point
    mp_results = np.array([v.result[:self.settings["T_MAX_OUTPUT"]+1] for v in self.variables])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 647. KiB for an array with shape (69, 1201) and data type object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\Projects\modelling\lifelib_cashflower\savings\run.py", line 9, in <module>
    output = start("savings", settings, sys.argv)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\Projects\modelling\venv\Lib\site-packages\cashflower\start.py", line 250, in start
    parts = pool.map(p, range(cpu_count))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 774, in get
    raise self._value
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 647. KiB for an array with shape (69, 1201) and data type object

Process finished with exit code 1
```

**Comment by zchmielewska** [comment]
The problem appeared when I tried to save results for all variables.

**Comment by zchmielewska** [comment]
Done in ebf7f37e8f1d3216d7a5000312d435a1a3a1bc9a
