### ISSUE TITLE
non-broadcastable output operand error

### ISSUE THREAD

**Issue by remdesivir6** [acturtle/cashflower#415]
A model run produces an error when:

- the main model point set contains at least 2 data points
- the model contains at least 2 variables (variable A and variable B) where variable A depends on the value of variable B
- the output columns list in settings is `["variable A"]`

An example to reproduce:

```python
# input.py
import pandas as pd
from cashflower import Runplan, ModelPointSet


runplan = Runplan(data=pd.DataFrame({"version": [1]}))

main = ModelPointSet(data=pd.DataFrame({"id": [1, 2]}))

assumption = dict()

```

```python
# run.py
import os
from cashflower import run
from settings import settings

if __name__ == "__main__":
    output = run(settings=settings, path=os.path.dirname(__file__))

```

```python
# model.py
from cashflower import variable


@variable()
def projection_year(t):
    if t == 0:
        return 0
    elif t % 12 == 1:
        return projection_year(t - 1) + 1
    else:
        return projection_year(t - 1) + projection_constant()


@variable()
def projection_constant():
    return 1

```

```python
# settings.py
settings = {
    "AGGREGATE": True,
    "GROUP_BY_COLUMN": None,
    "ID_COLUMN": "id",
    "MULTIPROCESSING": False,
    "NUM_STOCHASTIC_SCENARIOS": None,
    "OUTPUT_COLUMNS": ["projection_year"],
    "SAVE_DIAGNOSTIC": True,
    "SAVE_LOG": True,
    "SAVE_OUTPUT": True,
    "T_MAX_CALCULATION": 720,
    "T_MAX_OUTPUT": 720,
}
```

Traceback from executing `python wol/run.py`:
```
Traceback (most recent call last):
  File "wol/run.py", line 6, in <module>
    output = run(settings=settings, path=os.path.dirname(__file__))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/cashflower/start.py", line 581, in run
    output, diagnostic = start_single_core(settings, args=args)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/cashflower/start.py", line 364, in start_single_core
    output, runtime = model.run()
                      ^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/cashflower/core.py", line 399, in run
    output = self.compute_aggregated_results(range_start, range_end, one_core)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/cashflower/core.py", line 451, in compute_aggregated_results
    results = self.agg_calculate_without_grouping(calculate_model_point_partial, batch_start, batch_end,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/cashflower/core.py", line 507, in agg_calculate_without_grouping
    results += batch_results * multiplier[:, None]
ValueError: non-broadcastable output operand with shape (1,721) doesn't match the broadcast shape (2,721)
```

**Comment by zchmielewska** [comment]
Hi @remdesivir6, thanks for raising the issue and providing a reproducible example.

The issue was caused by a bug in the `compute_aggregated_results` method, where the `multiplier` array was not correctly handling the output columns specified in the settings. Specifically, it was trying to aggregate variables that weren't included in the output columns, leading to a shape mismatch during aggregation.

This has now been fixed in version 0.7.3. The fix ensures that the `multiplier` only includes variables specified in the `OUTPUT_COLUMNS` setting. Please update to the latest version, and the issue should be resolved.
